version: "3.7"

services:
  item-app:
    build: .
    ports:
      - 80:8080
    depends_on:
      - item-db
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    restart: always

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always

volumes:
  app-db:
